#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

bspc monitor -d I II III IV V VI VII 
bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a floorp desktop='^2'follow=on
bspc rule -a thunderbird desktop='^7'follow=on
bspc rule -a discord desktop='^4'
bspc rule -a github-desktop desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule --add program state=floating rectangle=WxH+X+Y

# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
# Wallpaper
variety &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
picom -b &

# Network Applet
nm-applet --indicator &

# discord
com.discordapp.Discord --no-sandbox --ignore-gpu-blocklist --disable-features=UseOzonePlatform --enable-features=VaapiVideoDecoder --use-gl=desktop --enable-gpu-rasterization --enable-zero-copy &

# Flameshot
/usr/bin/flameshot &

# GreenClip - Clipboard Manager
/usr/bin/greenclip daemon &

#thunderbird
/usr/bin/thunderbird &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh


