import = ["/home/hazelnut/.config/alacritty/themes/themes/catppuccin.yml"]

[font]
size = 11.5

[font.bold]
family = "MonaspiceNeNerdFont"
style = "Bold"

[font.italic]
family = "MonaspiceRnNerdFont"
style = "Italic"

[font.normal]
family = "MonaspiceNeNerdFont"
style = "Regular"

[font.offset]
x = 1
y = 0

[shell]
args = ["-l", "-c", "tmux -u attach || tmux -u"]
program = "/bin/fish"

[window]
dynamic_padding = false
opacity = 0.98
startup_mode = "Maximized"

[window.padding]
x = 10
y = 10
