import:
  - ~/.config/alacritty/themes/themes/catppuccin.yaml
window:
  dynamic_padding: false
  decorations: none
  opacity: 0.98
  padding:
    x: 10
    y: 10
font:
  size: 11.5
  normal:
    family: CaskaydiaCove Nerd Font
    style: Regular
  bold:
    family: CaskaydiaCove Nerd Font
    style: Bold
  italic:
    family: CaskaydiaCove Nerd Font Mono
    style: Italic
  offset:
    x: 1
    y: 0
colors: {}
shell:
  program: /bin/fish
  args:
    - -l
    - -c
    - "tmux -u attach || tmux -u"

