import:
  - ~/.config/alacritty/themes/themes/catppuccin.toml
window:
  dynamic_padding: false
  opacity: 0.98
  startup_mode: "Maximized"
  padding:
    x: 10
    y: 10
font:
  size: 11.5
  normal:
    family: CaskaydiaCove NF
    style: Regular
  bold:
    family: CaskaydiaCove NF
    style: Bold
  italic:
    family: CaskaydiaMono NFM
    style: Italic
colors: {}
shell:
  program: /bin/fish
  args: 
    - -l
    - -c
    - "tmux -u attach || tmux -u"

