import = [ "~/.config/alacritty/themes/themes/catppuccin.yaml" ]

[window]
dynamic_padding = false
opacity = 0.98
startup_mode = "Maximized"

  [window.padding]
  x = 10
  y = 10

[font]
size = 11.5

  [font.normal]
  family = "FiraCode Nerd Font"
  style = "Regular"

  [font.bold]
  family = "CaskaydiaCove Nerd Font"
  style = "Bold"

  [font.italic]
  family = "CaskaydiaCove Nerd Font Mono"
  style = "Italic"

  [font.offset]
  x = 1
  y = 1

[colors]
[colors.primary]
background = "0x1a1b26"
foreground = "0xa9b1d6"

[colors.normal]
black = "0x32344a"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xad8ee6"
cyan = "0x449dab"
white = "0x787c99"

[colors.bright]
black = "0x444b6a"
red = "0xff7a93"
green = "0xb9f27c"
yellow = "0xff9e64"
blue = "0x7da6ff"
magenta = "0xbb9af7"
cyan = "0x0db9d7"
white = "0xacb0d0"


[shell]
program = "/bin/fish"

